include colors.conf
# Font
font_family      JetBrainsMono Nerd Font
font_size        11.5
disable_ligatures never

# Window
window_padding_width 12
background_opacity   0.92
confirm_os_window_close 0

# Cursor
cursor_shape           beam
cursor_beam_thickness  1.8
cursor_blink_interval  0.5

# Tabs
tab_bar_edge          top
tab_bar_style         powerline
tab_powerline_style   slanted
tab_bar_min_tabs      2

# Behaviour
scrollback_lines      10000
enable_audio_bell     no
url_style             curly
