-- The matugen palette (colors.lua, generated by setwall) with a fallback so
-- the config loads before the first wallpaper has been set. Hex without '#'.
local ok, res = pcall(dofile, os.getenv("HOME") .. "/.config/hypr/colors.lua")
if ok and type(res) == "table" then
    return res
end
return {
    primary   = "83d5c6",
    secondary = "b1ccc5",
    tertiary  = "accae5",
    outline   = "899390",
    surface   = "0e1513",
}
