[config]
[templates.waybar]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook = 'pkill -SIGUSR2 waybar'

[templates.swaync]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/swaync/colors.css'
post_hook = 'swaync-client -rs'

[templates.hyprland]
input_path = '~/.config/matugen/templates/hypr-colors.lua'
output_path = '~/.config/hypr/colors.lua'
post_hook = 'hyprctl reload'

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty-colors.conf'
output_path = '~/.config/kitty/colors.conf'
post_hook = 'pkill -SIGUSR1 kitty'

[templates.hyprlock]
input_path = '~/.config/matugen/templates/hyprlock-colors.conf'
output_path = '~/.config/hypr/hyprlock-colors.conf'

[templates.fuzzel]
input_path = '~/.config/matugen/templates/fuzzel-colors.ini'
output_path = '~/.config/fuzzel/colors.ini'

[templates.colorsh]
input_path = '~/.config/matugen/templates/colors.sh'
output_path = '~/.config/matugen/colors.sh'

[config.custom_colors]
ansi_red     = { color = "#ff0000", blend = true }
ansi_green   = { color = "#00c000", blend = true }
ansi_yellow  = { color = "#e0c000", blend = true }
ansi_blue    = { color = "#0060ff", blend = true }
ansi_magenta = { color = "#c000c0", blend = true }
ansi_cyan    = { color = "#00c0c0", blend = true }

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/colors.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-{{mode}}'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/colors.css'

[templates.kde]
input_path = '~/.config/matugen/templates/Matugen.colors'
output_path = '~/.local/share/color-schemes/Matugen.colors'

[templates.vscode-raw]
input_path = '~/.config/matugen/templates/vscode-colors'
output_path = '~/.cache/matugen/vscode-colors'

[templates.vscode-json]
input_path = '~/.config/matugen/templates/vscode-colors.json'
output_path = '~/.cache/matugen/vscode-colors.json'
