"""Rounding, opacity, blur, shadows, animations. Colours are not here: the
palette in conf/look.lua follows the wallpaper."""
from . import OptionsPage

PAGE = OptionsPage("Look", "󰏘", 30, [
    ("Windows", None),
    "decoration:rounding",
    "decoration:rounding_power",
    "decoration:active_opacity",
    "decoration:inactive_opacity",
    "decoration:fullscreen_opacity",
    "decoration:dim_inactive",
    "decoration:dim_strength",
    "decoration:dim_special",
    ("Blur", None),
    "decoration:blur:enabled",
    "decoration:blur:size",
    "decoration:blur:passes",
    "decoration:blur:vibrancy",
    "decoration:blur:noise",
    "decoration:blur:contrast",
    "decoration:blur:brightness",
    "decoration:blur:xray",
    "decoration:blur:popups",
    ("Shadow", None),
    "decoration:shadow:enabled",
    "decoration:shadow:range",
    "decoration:shadow:render_power",
    "decoration:shadow:sharp",
    ("Motion", None),
    "animations:enabled",
    "animations:workspace_wraparound",
    "misc:animate_manual_resizes",
    "misc:animate_mouse_windowdragging",
    ("Rendering", None),
    "render:new_render_scheduling",
    "misc:vrr",
    "render:direct_scanout",
    "misc:disable_hyprland_logo",
    "misc:disable_splash_rendering",
    "misc:background_color",
])
