"""Tiling: layout, gaps, borders, and the per-layout knobs."""
from . import OptionsPage

PAGE = OptionsPage("Windows", "󱂬", 20, [
    ("Layout", None),
    "general:layout",
    "general:gaps_in",
    "general:gaps_out",
    "general:gaps_workspaces",
    "general:border_size",
    "general:resize_on_border",
    "general:extend_border_grab_area",
    "general:no_focus_fallback",
    ("Snapping (floating windows)", None),
    "general:snap:enabled",
    "general:snap:window_gap",
    "general:snap:monitor_gap",
    "general:snap:border_overlap",
    ("Dwindle", None),
    "dwindle:preserve_split",
    "dwindle:force_split",
    "dwindle:smart_split",
    "dwindle:smart_resizing",
    "dwindle:split_width_multiplier",
    "dwindle:default_split_ratio",
    "dwindle:special_scale_factor",
    ("Master", None),
    "master:new_status",
    "master:new_on_top",
    "master:orientation",
    "master:mfact",
    "master:slave_count_for_center_master",
    "master:special_scale_factor",
    ("Scrolling", None),
    "scrolling:fullscreen_on_one_column",
    "scrolling:column_width",
    "scrolling:focus_fit_method",
    "scrolling:follow_focus",
    ("Focus", None),
    "misc:focus_on_activate",
    "input:focus_on_close",
    "misc:mouse_move_focuses_monitor",
    "misc:initial_workspace_tracking",
])
