-- generated by matugen (templates/swayimg-colors.lua); read by swayimg/init.lua
return {
  surface = "{{colors.surface.default.hex_stripped}}",
  on_surface = "{{colors.on_surface.default.hex_stripped}}",
  on_surface_variant = "{{colors.on_surface_variant.default.hex_stripped}}",
  primary = "{{colors.primary.default.hex_stripped}}",
  primary_container = "{{colors.primary_container.default.hex_stripped}}",
  surface_container_high = "{{colors.surface_container_high.default.hex_stripped}}",
  tertiary = "{{colors.tertiary.default.hex_stripped}}",
  outline = "{{colors.outline.default.hex_stripped}}",
}
