local C
do
    local ok, res = pcall(dofile, os.getenv("HOME") .. "/.config/hypr/colors.lua")
    if ok and type(res) == "table" then
        C = res
    else
        C = {
            primary   = "83d5c6",
            secondary = "b1ccc5",
            tertiary  = "accae5",
            outline   = "899390",
            surface   = "0e1513",
        }
    end
end

-- Layout profile, written by ~/.local/bin/relayout. Read here so the window
-- rules below survive a `hyprctl reload` (matugen fires one on every wallpaper
-- change, and reload drops anything injected with `hyprctl eval`).
local LP = { dash_ws = 1, work_ws = 2, stash_ws = "special:magic",
             used_re = "^(Spotify|slack|discord|layout-sysmon|layout-term)$",
             guard_re = "negative:^(Spotify|slack|discord|layout-sysmon|layout-term|cheatsheet|hyprland-run)$",
             -- bootstrap fallback only; relayout owns the real map
             ws_home = { [1] = "HDMI-A-1", [2] = "HDMI-A-1", [3] = "HDMI-A-1",
                         [4] = "HDMI-A-1", [5] = "HDMI-A-1",
                         [6] = "DP-2",     [7] = "DP-2",     [8] = "DP-2",
                         [9] = "HDMI-A-2", [10] = "HDMI-A-2" } }
do
    local ok, res = pcall(dofile, os.getenv("HOME") .. "/.cache/relayout-state.lua")
    if ok and type(res) == "table" and res.dash_ws then LP = res end
end

require("monitors")
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- AUTOGENERATED HYPRLAND CONFIG.                        --
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.  --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --


-- This is an example Hyprland Lua config file.
-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/Start/

-- Please note not all available settings / options are set here.
-- For a full list, see the wiki

-- You can (and should!!) split this configuration into multiple files
-- Create your files separately and then require them like this:
-- require("myColors")


------------------
---- MONITORS ----
------------------

-- See https://wiki.hypr.land/Configuring/Basics/Monitors/
hl.monitor({
    output   = "",
    mode     = "preferred",
    position = "auto",
    scale    = "auto",
})


---------------------
---- MY PROGRAMS ----
---------------------

-- Set programs that you use
local terminal    = "kitty"
local fileManager = "dolphin"
local menu = os.getenv("HOME") .. "/.local/bin/rofi-launcher"


-------------------
---- AUTOSTART ----
-------------------

-- See https://wiki.hypr.land/Configuring/Basics/Autostart/

-- Autostart necessary processes (like notifications daemons, status bars, etc.)
-- Or execute your favorite apps at launch like this:
--
-- hl.on("hyprland.start", function () 
--   hl.exec_cmd(terminal)
--   hl.exec_cmd("nm-applet")
--   hl.exec_cmd("waybar & hyprpaper & firefox")
-- end)

hl.on("hyprland.start", function()
    -- Chained with && inside ONE exec_cmd on purpose: exec_cmd is async, so as
    -- separate lines the environment import races the services that need it.
    --
    -- xdg-desktop-portal picks its backends from XDG_CURRENT_DESKTOP when it
    -- starts and caches that choice for its lifetime. Started before the import
    -- (anything requesting a portal will D-Bus activate it), it comes up with
    -- only the gtk backend, which provides no ScreenCast on Hyprland — so
    -- screen sharing silently has no interface to call. Restarting it here
    -- makes it pick up xdg-desktop-portal-hyprland.
    -- HYPRLAND_INSTANCE_SIGNATURE is imported for waybar: its hyprland/*
    -- modules find the compositor's IPC socket at
    -- $XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock. Launched
    -- by Hyprland it inherited that; started by systemd it does not, and the
    -- workspace and submap modules come up empty without it.
    --
    -- waybar.service hangs off graphical-session.target (Requisite= and
    -- WantedBy=), but that target sets RefuseManualStart and can only be
    -- reached as a dependency - hence hyprland-session.target, which BindsTo it.
    -- Starting ours pulls graphical-session.target up and waybar with it, and
    -- brings both down when the session ends. Nothing else is enabled there.
    --
    -- `restart`, not `start`, and this is load-bearing. Nothing tears the
    -- target down when Hyprland goes away: the compositor dies (or is killed,
    -- or crashes - there is no exit hook that survives all three) and the
    -- target is simply left active. On the next login `start` then sees an
    -- already-active target, does nothing, and never re-runs its dependencies,
    -- so a waybar left in failed/start-limit-hit by the previous teardown stays
    -- down for the whole session with no bar and no error. `restart` stops the
    -- target first, which pulls graphical-session.target down through BindsTo
    -- and every PartOf unit with it, then brings the lot back against the
    -- WAYLAND_DISPLAY just imported. reset-failed clears the previous session's
    -- wreckage so the fresh start is not refused by a still-live rate limit.
    -- Reconciling on the way in rather than hooking the way out is deliberate:
    -- a crash skips shutdown hooks, but login always happens.
    --
    -- reset-failed comes before either restart because a unit that tripped its
    -- start limit on the way out refuses to start on the way back in: systemd
    -- answers "Start request repeated too quickly" and the restart below is a
    -- no-op. hyprpolkitagent is in the list for exactly that reason - it aborts
    -- in Qt's DBus thread when the compositor disappears, burns its five
    -- restarts in under a second, and was still inside its rate-limit window
    -- when the next session asked for it, leaving the session with no polkit
    -- agent and so no authentication prompts at all.
    hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP HYPRLAND_INSTANCE_SIGNATURE && (systemctl --user reset-failed hyprpolkitagent xdg-desktop-portal waybar.service hyprland-session.target 2>/dev/null || true) && systemctl --user restart hyprpolkitagent xdg-desktop-portal && systemctl --user restart hyprland-session.target")
    hl.exec_cmd("swaync")
    -- waybar runs as a systemd user unit rather than a bare exec_cmd: it
    -- segfaults in its mpris module when a player (Chrome) goes away, and
    -- Restart=on-failure brings it straight back instead of leaving no bar.
    -- Started above via graphical-session.target; `journalctl --user -u waybar`
    -- now has its output, which a fire-and-forget exec_cmd threw away.
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd("hypridle")
    -- Spotify's colours come from a matugen-generated color.ini in the Text
    -- theme folder. Rewriting that file is not enough on its own: `spicetify
    -- refresh` updates the client's files but leaves a running Spotify painted
    -- with the old scheme, and `spicetify apply` would restart it and stop
    -- playback. `watch -s` sees the color.ini change and reloads the running
    -- client in place, which is the only path that repaints without a restart.
    hl.exec_cmd("spicetify watch -s")
    -- relayout --boot launches every dashboard app that is not already
    -- running and waits for it to map. Launching them here as well raced
    -- with that check and produced duplicate kitty windows.
    hl.exec_cmd("/home/holla/.local/bin/relayout --boot")
end)

-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Environment-variables/

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("QT_QPA_PLATFORMTHEME", "kde")

-----------------------
----- PERMISSIONS -----
-----------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Permissions/
-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly
-- for security reasons

-- hl.config({
--   ecosystem = {
--     enforce_permissions = true,
--   },
-- })

-- hl.permission("/usr/(bin|local/bin)/grim", "screencopy", "allow")
-- hl.permission("/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland", "screencopy", "allow")
-- hl.permission("/usr/(bin|local/bin)/hyprpm", "plugin", "allow")


-----------------------
---- LOOK AND FEEL ----
-----------------------

-- Refer to https://wiki.hypr.land/Configuring/Basics/Variables/
hl.config({
    general = {
        gaps_in  = 5,
        gaps_out = 20,

        border_size = 2,

        col = {
            active_border = {
                colors = { "rgba(" .. C.primary .. "ee)", "rgba(" .. C.tertiary .. "ee)" },
          angle = 45,
            },
            inactive_border = "rgba(" .. C.outline .. "66)",
        },

        -- Set to true to enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = false,

        -- Please see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Tearing/ before you turn this on
        allow_tearing = false,

        layout = "dwindle",
    },

    decoration = {
        rounding       = 10,
        rounding_power = 2,

        -- Change transparency of focused and unfocused windows
        active_opacity   = 1.0,
        inactive_opacity = 1.0,

        shadow = {
            enabled      = true,
            range        = 4,
            render_power = 3,
            color        = 0xee1a1a1a,
        },

        blur = {
            enabled   = true,
            size      = 3,
            passes    = 1,
            vibrancy  = 0.1696,
        },
    },

    animations = {
        enabled = true,
    },
})

-- Default curves and animations, see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Animations/
hl.curve("easeOutQuint",   { type = "bezier", points = { {0.23, 1},    {0.32, 1}    } })
hl.curve("easeInOutCubic", { type = "bezier", points = { {0.65, 0.05}, {0.36, 1}    } })
hl.curve("linear",         { type = "bezier", points = { {0, 0},       {1, 1}       } })
hl.curve("almostLinear",   { type = "bezier", points = { {0.5, 0.5},   {0.75, 1}    } })
hl.curve("quick",          { type = "bezier", points = { {0.15, 0},    {0.1, 1}     } })

-- Default springs
hl.curve("easy",           { type = "spring", mass = 1, stiffness = 238.1191, dampening = 24.21279333 })

hl.animation({ leaf = "global",        enabled = true,  speed = 10,   bezier = "default" })
hl.animation({ leaf = "border",        enabled = true,  speed = 5.39, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows",       enabled = true,  speed = 4.79, spring = "easy" })
hl.animation({ leaf = "windowsIn",     enabled = true,  speed = 4.1,  spring = "easy",         style = "popin 87%" })
hl.animation({ leaf = "windowsOut",    enabled = true,  speed = 1.49, bezier = "linear",       style = "popin 87%" })
hl.animation({ leaf = "fadeIn",        enabled = true,  speed = 1.73, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut",       enabled = true,  speed = 1.46, bezier = "almostLinear" })
hl.animation({ leaf = "fade",          enabled = true,  speed = 3.03, bezier = "quick" })
hl.animation({ leaf = "layers",        enabled = true,  speed = 3.81, bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn",      enabled = true,  speed = 4,    bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut",     enabled = true,  speed = 1.5,  bezier = "linear",       style = "fade" })
hl.animation({ leaf = "fadeLayersIn",  enabled = true,  speed = 1.79, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true,  speed = 1.39, bezier = "almostLinear" })
hl.animation({ leaf = "workspaces",    enabled = true,  speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesIn",  enabled = true,  speed = 1.21, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesOut", enabled = true,  speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "zoomFactor",    enabled = true,  speed = 7,    bezier = "quick" })

-- Ref https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/
-- "Smart gaps" / "No gaps when only"
-- uncomment all if you wish to use that.
-- hl.workspace_rule({ workspace = "w[tv1]", gaps_out = 0, gaps_in = 0 })
-- hl.workspace_rule({ workspace = "f[1]",   gaps_out = 0, gaps_in = 0 })
-- hl.window_rule({
--     name  = "no-gaps-wtv1",
--     match = { float = false, workspace = "w[tv1]" },
--     border_size = 0,
--     rounding    = 0,
-- })
-- hl.window_rule({
--     name  = "no-gaps-f1",
--     match = { float = false, workspace = "f[1]" },
--     border_size = 0,
--     rounding    = 0,
-- })

hl.window_rule({
    name  = "cheatsheet-float",
    match = { class = "^cheatsheet$" },

    float       = true,
    size        = "1560 500",   -- two columns of keybinds at kitty's 11.5pt
    center      = true,
    border_size = 0,
})

-- Ordinary windows tile normally on whatever workspace they open on, so
-- several can share one and be cycled with SUPER+TAB. The only workspace
-- that is protected is the one the dashboard currently occupies.
--
-- Rule order matters: later rules win, so the guard is declared first and
-- the dashboard apps re-claim the workspace after it.

-- The guard skips the dashboard apps themselves and deliberate overlays such
-- as the cheatsheet, which are supposed to appear on top of whatever is on
-- screen. Hyprland's matcher has no boolean negation; the "negative:" prefix
-- on the value is what inverts the match.
hl.window_rule({
    name  = "relayout-dash-guard",
    match = { workspace = tostring(LP.dash_ws), class = LP.guard_re },
    -- deliberately not "silent": you should see the window you just opened
    workspace = tostring(LP.work_ws),
})

hl.window_rule({
    name  = "relayout-dash-apps",
    match = { class = LP.used_re },
    workspace = LP.dash_ws .. " silent",
    float = true,
})

if LP.parked_re then
    hl.window_rule({
        name  = "relayout-dash-parked",
        match = { class = LP.parked_re },
        workspace = LP.stash_ws .. " silent",
        float = true,
    })
end

-- Every window is translucent; no per-app exceptions. When one needs to be
-- solid for a while (a video, a colour-sensitive image), SUPER+T toggles the
-- focused window's opaque flag, which wins over this rule until toggled back
-- or the window closes.
hl.window_rule({
    name  = "translucent-all",
    match = { class = ".*" },
    opacity = "0.95 override 0.85 override 1.0 override",
})

-- Bind every workspace to a monitor.
--
-- The r[N-M] range selector is accepted by the parser but never actually
-- matches: workspaces kept being created on whichever monitor happened to be
-- focused. Verified by focusing HDMI-A-2 and switching to ws2 — it was created
-- on HDMI-A-2 under the range rule, and on HDMI-A-1 once ws2 was named
-- explicitly. So enumerate them.
--
--   HDMI-A-1  1 = dashboard slot, 2 = work, 3-5 spare
--   DP-2      6 = dashboard slot, 7 = work, 8 spare
--   HDMI-A-2  9, 10
for ws = 1, 10 do
    local mon = LP.ws_home and LP.ws_home[ws]
    if mon then hl.workspace_rule({ workspace = tostring(ws), monitor = mon }) end
end

-- which workspace each monitor shows when it first appears
hl.workspace_rule({ workspace = "1", monitor = "HDMI-A-1", default = true })
hl.workspace_rule({ workspace = "6", monitor = "DP-2",     default = true })
hl.workspace_rule({ workspace = "9", monitor = "HDMI-A-2", default = true })

-- See https://wiki.hypr.land/Configuring/Layouts/Dwindle-Layout/ for more
hl.config({
    dwindle = {
        preserve_split = true, -- You probably want this
    },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Master-Layout/ for more
hl.config({
    master = {
        new_status = "master",
    },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Scrolling-Layout/ for more
hl.config({
    scrolling = {
        fullscreen_on_one_column = true,
    },
})

----------------
----  MISC  ----
----------------

hl.config({
    misc = {
        force_default_wallpaper = 0,    -- Set to 0 or 1 to disable the anime mascot wallpapers
        disable_hyprland_logo   = true, -- If true disables the random hyprland logo / anime girl background. :(
    },
})


---------------
---- INPUT ----
---------------

hl.config({
    input = {
        kb_layout  = "us",
        kb_variant = "",
        kb_model   = "",
        kb_options = "",
        kb_rules   = "",

        follow_mouse = 1,

        sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.

        touchpad = {
            natural_scroll = false,
        },
    },
})

hl.gesture({
    fingers = 3,
    direction = "horizontal",
    action = "workspace"
})

-- Example per-device config
-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Devices/ for more
hl.device({
    name        = "epic-mouse-v1",
    sensitivity = -0.5,
})


---------------------
---- KEYBINDINGS ----
---------------------

local mainMod = "SUPER" -- Sets "Windows" key as main modifier

-- Example binds, see https://wiki.hypr.land/Configuring/Basics/Binds/ for more
hl.bind(mainMod .. " + Q", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.exec_cmd('grim -g "$(slurp)" - | wl-copy'))
hl.bind(mainMod .. " + SHIFT + N", hl.dsp.exec_cmd("swaync-client -t -sw"))
hl.bind(mainMod .. " + slash", hl.dsp.exec_cmd("kitty --class cheatsheet -e ~/.local/bin/cheatsheet"))
hl.bind(mainMod .. " + SHIFT + C", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.local/bin/rofi-cliphist"))
hl.bind(mainMod .. " + L", hl.dsp.exec_cmd("hyprlock"))
-- lock: without it the translucent-all rule is re-applied on every focus
-- change and fights the prop (visible as flicker while hovering)
hl.bind(mainMod .. " + T", hl.dsp.window.set_prop({ prop = "opaque", value = "toggle", lock = true }))
hl.bind(mainMod .. " + W", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.local/bin/wallstrip"))
hl.bind(mainMod .. " + SHIFT + R", hl.dsp.exec_cmd("/home/holla/.local/bin/relayout"))
hl.bind(mainMod .. " + ALT + R",   hl.dsp.exec_cmd("/home/holla/.local/bin/relayout toggle"))

-- Cycle windows on the current workspace (there was no alt-tab bind at all).
-- Forward only: cycle_next accepts "prev" / { prev = true } / { last = true }
-- without complaining but ignores every one of them and always steps forward
-- (checked against a known cycle order with four windows), so a reverse bind
-- would silently do the wrong thing. SUPER + arrows moves focus spatially.
hl.bind(mainMod .. " + TAB", hl.dsp.window.cycle_next())
hl.bind("ALT + TAB",         hl.dsp.window.cycle_next())

-- Move windows with mainMod + SHIFT + arrow keys
hl.bind(mainMod .. " + SHIFT + left",  hl.dsp.window.move({ direction = "left" }))
hl.bind(mainMod .. " + SHIFT + right", hl.dsp.window.move({ direction = "right" }))
hl.bind(mainMod .. " + SHIFT + up",    hl.dsp.window.move({ direction = "up" }))
hl.bind(mainMod .. " + SHIFT + down",  hl.dsp.window.move({ direction = "down" }))

local closeWindowBind = hl.bind(mainMod .. " + C", hl.dsp.window.close())
-- closeWindowBind:set_enabled(false)
hl.bind(mainMod .. " + M", hl.dsp.exec_cmd("command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch 'hl.dsp.exit()'"))
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + V", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + R", hl.dsp.exec_cmd(menu))
hl.bind(mainMod .. " + P", hl.dsp.window.pseudo())
-- "Fake" fullscreen: the client is TOLD it is fullscreen (so it drops its own
-- chrome and renders a fullscreen layout) while Hyprland leaves the window at
-- its normal tiled geometry. Verified live: size stayed [961, 671] with
-- fullscreenClient going 0 -> 2.
--
-- Not the old `fakefullscreen` dispatcher, which is gone in 0.56. The API is
-- fullscreen_state{ internal, client } where both are REQUIRED and take the
-- mode ints 0 = none, 1 = maximized, 2 = fullscreen. internal = 0 is what
-- keeps the window its current size; client = 2 is the lie the app is told.
-- action = "toggle" makes the one bind flip both ways.
--
-- SUPER + SHIFT + F is real fullscreen, for when you do want the whole screen.
hl.bind(mainMod .. " + F", hl.dsp.window.fullscreen_state({ internal = 0, client = 2, action = "toggle" }))
hl.bind(mainMod .. " + SHIFT + F", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }))
hl.bind(mainMod .. " + J", hl.dsp.layout("togglesplit"))    -- dwindle only

-- Move focus with mainMod + arrow keys
hl.bind(mainMod .. " + left",  hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up",    hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down",  hl.dsp.focus({ direction = "down" }))

-- Switch workspaces with mainMod + [0-9]
-- Move active window to a workspace with mainMod + SHIFT + [0-9]
for i = 1, 10 do
    local key = i % 10 -- 10 maps to key 0
    hl.bind(mainMod .. " + " .. key,             hl.dsp.focus({ workspace = i}))
    hl.bind(mainMod .. " + SHIFT + " .. key,     hl.dsp.window.move({ workspace = i }))
end

-- Example special workspace (scratchpad)
hl.bind(mainMod .. " + S",         hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + ALT + S", hl.dsp.window.move({ workspace = "special:magic" }))

-- Scroll through existing workspaces with mainMod + scroll
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up",   hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(),   { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Laptop multimedia keys for volume and LCD brightness
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),      { locked = true, repeating = true })
hl.bind("XF86AudioMute",        hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),     { locked = true, repeating = true })
hl.bind("XF86AudioMicMute",     hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"),   { locked = true, repeating = true })
hl.bind("XF86MonBrightnessUp",  hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"),                  { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown",hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"),                  { locked = true, repeating = true })

-- Requires playerctl
hl.bind("XF86AudioNext",  hl.dsp.exec_cmd("playerctl next"),       { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay",  hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev",  hl.dsp.exec_cmd("playerctl previous"),   { locked = true })


--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

-- See https://wiki.hypr.land/Configuring/Basics/Window-Rules/
-- and https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/

-- Example window rules that are useful

local suppressMaximizeRule = hl.window_rule({
    -- Ignore maximize requests from all apps. You'll probably like this.
    name  = "suppress-maximize-events",
    match = { class = ".*" },

    suppress_event = "maximize",
})
-- suppressMaximizeRule:set_enabled(false)

hl.window_rule({
    -- Fix some dragging issues with XWayland
    name  = "fix-xwayland-drags",
    match = {
        class      = "^$",
        title      = "^$",
        xwayland   = true,
        float      = true,
        fullscreen = false,
        pin        = false,
    },

    no_focus = true,
})

-- Layer rules also return a handle.
-- local overlayLayerRule = hl.layer_rule({
--     name  = "no-anim-overlay",
--     match = { namespace = "^my-overlay$" },
--     no_anim = true,
-- })
-- overlayLayerRule:set_enabled(false)

-- Frosted popups: blur the wallpaper behind the bar, its launcher menu, the
-- swaync panels and volpop. Their stylesheets paint translucent @surface so
-- the blur shows through; ignore_alpha keeps the fully transparent parts of
-- the surfaces (swaync's screen-wide window, volpop's click-away backdrop)
-- from being blurred as well.
for _, r in ipairs({
    { name = "frosted-waybar",  ns = "^waybar$",                      popups = true },
    { name = "frosted-swaync",  ns = "^swaync-control-center$" },
    { name = "frosted-notifs",  ns = "^swaync-notification-window$" },
    { name = "frosted-volpop",  ns = "^volpop$" },
    { name = "frosted-wallstrip", ns = "^wallstrip$" },
}) do
    hl.layer_rule({
        name         = r.name,
        match        = { namespace = r.ns },
        blur         = true,
        blur_popups  = r.popups or false,
        ignore_alpha = 0.2,
    })
end

-- Hyprland-run windowrule
hl.window_rule({
    name  = "move-hyprland-run",
    match = { class = "hyprland-run" },

    move  = "20 monitor_h-120",
    float = true,
})
