-- Hyprland config entry point. Read natively by Hyprland >= 0.56 (Lua 5.5).
-- https://wiki.hypr.land/Configuring/Start/
--
--   conf/       the hand-written defaults, one topic per file
--   lib/        helpers: palette (matugen colours), actions registry, settings overrides, json
--   state/      what the settings UI (Arch button > Settings) wrote; applied last, so it wins
--   user/       optional: user/init.lua is loaded if present, for machine-local extras
--   monitors.lua  generated by nwg-displays
--   colors.lua    generated by setwall (matugen)
--
-- `hyprctl reload` recreates the Lua state and runs this file again, so every
-- module below re-runs on reload; matugen triggers one per wallpaper change.
-- Only conf/autostart.lua's hyprland.start handler is start-only.
local HOME = os.getenv("HOME")

local function report(what, err)
    hl.notification.create({ text = "hyprland.lua: " .. what .. " failed: " .. tostring(err), timeout = 10000 })
end

require("conf.env")
require("monitors")
require("conf.look")
require("conf.input")
require("conf.rules")
require("conf.autostart")
require("conf.actions")

-- user/init.lua: extra actions, hl.config tweaks, anything. A broken file
-- must not take the whole config down, hence the pcall.
local user_init = io.open(HOME .. "/.config/hypr/user/init.lua", "r")
if user_init then
    user_init:close()
    local ok, err = pcall(require, "user")
    if not ok then report("user/init.lua", err) end
end

-- Settings UI overrides last, then the binds (which merge their own overrides),
-- then the export the cheatsheet and the UI read.
local ok, err = pcall(function() require("lib.settings").apply() end)
if not ok then report("settings", err) end

local A = require("lib.actions")
A.bind_all()
A.export()
