-- Generated by gen-monitors on 2026-09-04 at 19:32:06. Do not edit manually.
-- (nwg-displays writes this file too, in the same shape.)

hl.monitor({
    output = "DP-2",
    mode = "1920x1080@143.86",
    position = "0x192",
    scale = 1,
    vrr = 0
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "2560x1440@144",
    position = "1920x0",
    scale = 1,
    vrr = 0
})
hl.monitor({
    output = "HDMI-A-2",
    mode = "1920x1080@144",
    position = "4480x192",
    scale = 1,
    vrr = 0
})
