-- Generated by nwg-displays on 2026-09-01 at 13:57:22. Do not edit manually.

hl.monitor({
    output = "HDMI-A-1",
    mode = "2560x1440@144.0",
    position = "1920x0",
    scale = 1.0,
    vrr = 0
})
hl.monitor({
    output = "HDMI-A-2",
    mode = "1920x1080@144.0",
    position = "4480x192",
    scale = 1,
    vrr = 0
})
hl.monitor({
    output = "DP-2",
    mode = "1920x1080@143.86",
    position = "0x192",
    scale = 1,
    vrr = 0
})
