import QtQuick
import QtQuick.Layouts
import Quickshell
import qs.Theme
import qs.Widgets
import qs.Services

// Config & logs: the files behind every other page, and the levers to reload.
//     Hyprland    reload (then `hyprctl configerrors`), version, error count
//     Files       one row per config file, each opens in the editor:
//                 $VISUAL / $EDITOR (asked of the login shell when the
//                 systemd session has neither), else nano, else vi. GUI
//                 editors are launched directly, terminal ones inside kitty
//     Shell       quickshell version, its journal, restart, re-apply wallpaper
//     Overrides   what the settings UI has written to state/*.json, and the
//                 two "reset everything" rows (click twice)
PageBody {
    id: root
    title: "Config & logs"
    subtitle: "The files behind these settings, reload and logs"
    readonly property string home: Quickshell.env("HOME")
    readonly property string hyprDir: Hypr.hyprDir
    readonly property string prefsPath: Prefs.path
    property string hyprVersion: ""
    property string qsVersion: ""
    property var configErrors: []
    property string editor: ""
    property bool editorGui: false
    property var sizes: ({})          // path -> "1.2 KiB" | "missing"
    property string armed: ""

    readonly property var files: [
        { label: "hyprland.lua", path: hyprDir + "/hyprland.lua", hint: "Entry point; loads everything below in order", keywords: "main entry" },
        { label: "conf/env.lua", path: hyprDir + "/conf/env.lua", hint: "Environment variables and cursor size", keywords: "environment variables xcursor" },
        { label: "conf/autostart.lua", path: hyprDir + "/conf/autostart.lua", hint: "What starts with the session", keywords: "startup exec-once" },
        { label: "conf/look.lua", path: hyprDir + "/conf/look.lua", hint: "Gaps, borders, rounding, blur, animations", keywords: "decoration appearance" },
        { label: "conf/input.lua", path: hyprDir + "/conf/input.lua", hint: "Keyboard, mouse and touchpad defaults", keywords: "keyboard mouse touchpad" },
        { label: "conf/rules.lua", path: hyprDir + "/conf/rules.lua", hint: "Window and layer rules", keywords: "windowrule layerrule" },
        { label: "conf/actions.lua", path: hyprDir + "/conf/actions.lua", hint: "Every action and its default keys", keywords: "keybinds binds actions terminal" },
        { label: "monitors.lua", path: hyprDir + "/monitors.lua", hint: "Generated by nwg-displays; the Displays page edits it", keywords: "displays outputs" },
        { label: "state/settings.json", path: hyprDir + "/state/settings.json", hint: "Option overrides written by these pages", keywords: "overrides options" },
        { label: "state/keybinds.json", path: hyprDir + "/state/keybinds.json", hint: "Keybind overrides and custom actions", keywords: "binds custom" },
        { label: "state/monitors.json", path: hyprDir + "/state/monitors.json", hint: "Per-monitor settings from the Displays page", keywords: "displays" },
        { label: "hypridle.conf", path: hyprDir + "/hypridle.conf", hint: "Idle timeouts: lock, screen off, suspend", keywords: "idle lock dpms suspend power" },
        { label: "quickshell/", path: home + "/.config/quickshell", hint: "The shell itself: bar, popups, this window", keywords: "qml shell directory" },
        { label: "quickshell prefs.json", path: prefsPath, hint: "The shell's own preferences (bar, clock, OSD, notifications)", keywords: "prefs shell state" }
    ]

    // ── editor ──
    readonly property string resolveEditor:
        'ed="${VISUAL:-${EDITOR:-}}"; '
        + 'if [ -z "$ed" ] && [ -n "$SHELL" ]; then ed="$("$SHELL" -lc \'echo "$VISUAL"; echo "$EDITOR"\' 2>/dev/null | grep -m1 .)"; fi; '
        + '[ -z "$ed" ] && { if command -v nano >/dev/null 2>&1; then ed=nano; else ed=vi; fi; }; '
        + 'gui=0; case "${ed##*/}" in codium*|code*|kate|kwrite|gedit|gnome-text-editor|mousepad|subl*|zed*|zeditor) gui=1;; esac; '
    function edit(path) {
        Overlays.settingsToggle()
        Proc.detach(["sh", "-c",
            'f="$0"; ' + resolveEditor
            + 'if [ "$gui" = 1 ]; then exec $ed "$f"; fi; '
            + 'if [ -d "$f" ]; then exec xdg-open "$f"; fi; '
            + 'exec kitty --title edit sh -c "exec $ed \\"\\$0\\"" "$f"',
            path])
    }
    function terminal(title, cmd) {
        Overlays.settingsToggle()
        Proc.detach(["kitty", "--title", title, "sh", "-c", cmd])
    }

    // ── reading ──
    function collect() {
        Proc.sh("hyprctl -j version; echo @@; qs --version; echo @@; " + resolveEditor + 'printf "%s\\n%s" "$ed" "$gui"; echo @@; '
                + "for f in " + files.map(f => JSON.stringify(f.path)).join(" ") + "; do if [ -e \"$f\" ]; then printf '%s=%s\\n' \"$f\" \"$(stat -Lc %s \"$f\")\"; else printf '%s=missing\\n' \"$f\"; fi; done",
        (code, out) => {
            const p = out.split("@@").map(s => s.trim())
            let hv = {}; try { hv = JSON.parse(p[0]) } catch (e) {}
            root.hyprVersion = hv.version ? hv.version + (hv.dirty ? " (dirty)" : "") : (p[0].split("\n")[0] || "")
            root.qsVersion = (p[1] || "").replace(/^Quickshell\s*/i, "").replace(/\(revision\s*,\s*/, "(")
            const ed = (p[2] || "").split("\n"); root.editor = ed[0] || ""; root.editorGui = (ed[1] || "").trim() === "1"
            const s = {}
            for (const line of (p[3] || "").split("\n")) {
                const eq = line.lastIndexOf("="); if (eq <= 0) continue
                const v = line.slice(eq + 1)
                s[line.slice(0, eq)] = v === "missing" ? "missing" : root.human(parseInt(v))
            }
            root.sizes = s
        })
        checkErrors(null)
    }
    function human(n) { return isNaN(n) ? "" : n < 1024 ? n + " B" : (n / 1024).toFixed(1) + " KiB" }
    function checkErrors(cb) {
        Hypr.json(["configerrors"], list => {
            root.configErrors = Array.isArray(list) ? list.filter(e => typeof e === "string" && e.trim().length) : []
            if (cb) cb()
        })
    }
    function reload() {
        root.status = "reloading…"; root.statusError = false
        Proc.run(["hyprctl", "reload"], (code, out, err) => {
            if (code !== 0) { root.status = "hyprctl reload: " + (err || out).trim(); root.statusError = true; return }
            errorsAfterReload.restart()
        })
    }
    Timer { id: errorsAfterReload; interval: 700; onTriggered: root.checkErrors(() => {
        root.statusError = root.configErrors.length > 0
        root.status = root.configErrors.length ? "reloaded with " + root.configErrors.length + " error" + (root.configErrors.length > 1 ? "s" : "") + ": " + root.configErrors[0] : "reloaded, no config errors"
    }) }
    Component.onCompleted: collect()

    // ── two clicks for the destructive rows ──
    function confirm(id, what, fn) {
        if (armed === id) { armed = ""; disarm.stop(); fn(); return }
        armed = id; root.status = what + " — click again to confirm"; root.statusError = false; disarm.restart()
    }
    Timer { id: disarm; interval: 5000; onTriggered: { root.armed = ""; if (root.status.indexOf("click again") >= 0) root.status = "" } }
    readonly property int overrideCount: Object.keys(Hypr.overrides).length
    readonly property int keybindCount: Object.keys(Hypr.keybinds.binds ?? {}).length + (Hypr.keybinds.custom ?? []).length
    function resetAllOptions() {
        const names = Object.keys(Hypr.overrides)
        for (const n of names) Hypr.resetOption(n)
        root.status = names.length ? "removed " + names.length + " override" + (names.length > 1 ? "s" : "") + "; Hyprland reloaded" : "nothing to reset"
        refreshAfterReset.restart()
    }
    Timer { id: refreshAfterReset; interval: 800; onTriggered: { if (Hypr.schemaLoaded) Hypr.loadSchema(true); root.collect() } }
    function resetAllKeybinds() {
        const n = keybindCount
        Hypr.saveKeybinds({ binds: {}, custom: [] })
        root.status = n ? "keybinds back to conf/actions.lua defaults; Hyprland reloaded" : "nothing to reset"
        refreshAfterReset.restart()
    }

    headerItems: [
        Pill { text: "󰑓  Reload Hyprland"; small: true; onClicked: root.reload() }
    ]

    Group {
        title: "Hyprland"
        SettingRow {
            label: "Reload config"
            hint: "Runs hyprland.lua again (hyprctl reload) and reports what configerrors says"
            keywords: "apply restart hyprctl"
            clickable: true
            onClicked: root.reload()
        }
        SettingRow {
            label: "Config errors"
            hint: root.configErrors.length ? root.configErrors[0] : "Nothing wrong at the last load"
            keywords: "problems broken lua"
            value: root.configErrors.length ? String(root.configErrors.length) : "none"
        }
        SettingRow {
            label: "Version"
            hint: "hyprctl version"
            keywords: "hyprland release build"
            value: root.hyprVersion || "…"
        }
    }

    Group {
        title: "Files"
        hint: "Each opens in " + (root.editor ? root.editor + (root.editorGui ? "" : " in kitty") : "your editor") + ". Folders open in the editor, or the file manager for a terminal editor."
        Repeater {
            model: root.files
            SettingRow {
                required property var modelData
                label: modelData.label
                hint: modelData.hint + (root.sizes[modelData.path] === "missing" ? "  ·  not created yet" : "")
                keywords: modelData.keywords + " " + modelData.path
                value: root.sizes[modelData.path] && root.sizes[modelData.path] !== "missing" ? root.sizes[modelData.path] : ""
                clickable: true
                onClicked: root.edit(modelData.path)
            }
        }
        SettingRow {
            label: "Editor"
            hint: "From $VISUAL or $EDITOR (asked of your login shell when the session has neither), else nano or vi"
            keywords: "codium code nano vim editor variable"
            value: root.editor ? root.editor + (root.editorGui ? "" : "  (terminal)") : "…"
        }
    }

    Group {
        title: "Shell (quickshell)"
        SettingRow {
            label: "Show log"
            hint: "journalctl --user -u quickshell -f in a terminal"
            keywords: "journal output warnings qml errors"
            clickable: true
            onClicked: root.terminal("quickshell log", "exec journalctl --user -u quickshell -f -n 200")
        }
        SettingRow {
            label: "Restart shell"
            hint: "systemctl --user restart quickshell; this window closes with it. Click twice."
            keywords: "systemd service reload bar"
            clickable: true
            onClicked: root.confirm("restart", "restart the shell", () => Proc.detach(["systemctl", "--user", "restart", "quickshell"]))
        }
        SettingRow {
            visible: hit && Wallpapers.current.length > 0
            label: "Re-apply wallpaper and palette"
            hint: "Runs setwall on the current wallpaper again: matugen regenerates colors.lua and every themed app"
            keywords: "matugen colours theme refresh regenerate"
            value: Wallpapers.current.split("/").pop()
            clickable: true
            onClicked: { Wallpapers.apply(Wallpapers.current); root.status = "setwall running…"; root.statusError = false }
        }
        SettingRow {
            label: "Version"
            hint: "qs --version"
            keywords: "quickshell release"
            value: root.qsVersion || "…"
        }
    }

    Group {
        title: "Overrides"
        advanced: true
        hint: "What these pages wrote over conf/*.lua. Resetting puts the hand-written defaults back; Hyprland reloads once per removed option."
        SettingRow {
            label: "Option overrides"
            hint: root.hyprDir + "/state/settings.json  ·  " + (root.sizes[root.hyprDir + "/state/settings.json"] || "")
                  + (root.overrideCount ? "  ·  " + Object.keys(Hypr.overrides).slice(0, 4).join(", ") + (root.overrideCount > 4 ? ", …" : "") : "")
            keywords: "settings.json options count"
            value: String(root.overrideCount)
        }
        SettingRow {
            label: "Reset all option overrides"
            hint: "Removes every key from state/settings.json; the ↺ on a single row does one. Click twice."
            keywords: "clear defaults settings.json"
            enabled: root.overrideCount > 0
            clickable: true
            onClicked: root.confirm("options", "remove " + root.overrideCount + " option override" + (root.overrideCount > 1 ? "s" : ""), root.resetAllOptions)
        }
        SettingRow {
            label: "Keybind overrides"
            hint: root.hyprDir + "/state/keybinds.json  ·  " + (root.sizes[root.hyprDir + "/state/keybinds.json"] || "")
            keywords: "keybinds.json binds custom count"
            value: String(root.keybindCount)
        }
        SettingRow {
            label: "Reset all keybinds"
            hint: "Empties state/keybinds.json: rebound keys and custom actions go, conf/actions.lua defaults come back. Click twice."
            keywords: "clear defaults keybinds.json custom actions"
            enabled: root.keybindCount > 0
            clickable: true
            onClicked: root.confirm("keybinds", "reset " + root.keybindCount + " keybind change" + (root.keybindCount > 1 ? "s" : ""), root.resetAllKeybinds)
        }
    }
}
